BaseDir "/var/run/collectd"
Include "/etc/collectd/conf.d/*.conf"
PIDFile "/var/run/collectd.pid"
PluginDir "/usr/lib/collectd"
TypesDB "/usr/share/collectd/types.db"
Interval 5
ReadThreads 4

LoadPlugin conntrack

LoadPlugin contextswitch

LoadPlugin cpu
<Plugin cpu>
	ValuesPercentage true
	ReportByCpu true
	ReportByState true
</Plugin>

LoadPlugin cpufreq

LoadPlugin dhcpleases
<Plugin dhcpleases>
	Path "/tmp/dhcp.leases"
</Plugin>

LoadPlugin dns
<Plugin dns>
	Interface "br-lan"
	Interface "eth0"
	Interface "eth1"
	Interface "pppoe-wan"
	Interface "tun0"
	Interface "phy0-ap0"
	Interface "phy1-ap0"
	IgnoreSource "127.0.0.1"
</Plugin>

LoadPlugin interface
<Plugin interface>
	IgnoreSelected true
</Plugin>

LoadPlugin ipstatistics

LoadPlugin iwinfo

LoadPlugin load

LoadPlugin memory
<Plugin memory>
	ValuesPercentage false
	ValuesAbsolute true
</Plugin>

LoadPlugin netlink
<Plugin netlink>
	IgnoreSelected true
</Plugin>

LoadPlugin network
<Plugin network>
	Server "IP_OF_TELEGRAF" "25826" # Telegraf IP
	Forward true
	ReportStats true
</Plugin>

LoadPlugin ping
<Plugin ping>
	TTL 127
	Interval 30
	Host "8.8.8.8"
	Host "8.8.4.4"
</Plugin>

LoadPlugin processes
<Plugin processes>
	Process "uhttpd"
	Process "dnsmasq"
	Process "dropbear"
</Plugin>

LoadPlugin rrdtool
<Plugin rrdtool>
	DataDir "/tmp/rrd"
	RRARows 288
	RRASingle true
	RRATimespan 7200
	RRATimespan 86400
	RRATimespan 604800
	RRATimespan 2678400
	RRATimespan 31622400
</Plugin>

LoadPlugin syslog
<Plugin syslog>
	LogLevel "debug"
	NotifyLevel "WARNING"
</Plugin>

LoadPlugin tcpconns
<Plugin tcpconns>
	ListeningPorts true
	AllPortsSummary true
	LocalPort 22
</Plugin>

LoadPlugin thermal

LoadPlugin uptime